"""make_training_fields_nullable

Revision ID: 2e66fba94864
Revises: a728b2d08d59
Create Date: 2026-02-23 15:21:35.108540

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2e66fba94864"
down_revision = "a728b2d08d59"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # batch_alter_table: most SQLite versions have no ALTER COLUMN, so it rebuilds the table there;
    # PostgreSQL gets the same ALTER statements as before.
    with op.batch_alter_table("model_basic") as batch_op:
        batch_op.alter_column("file_id", existing_type=sa.UUID(), nullable=True)
        batch_op.alter_column("model_type", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("training_split", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)
        batch_op.alter_column("optimizer", existing_type=sa.VARCHAR(length=50), nullable=True)
        batch_op.alter_column("metric", existing_type=sa.VARCHAR(length=50), nullable=True)
        batch_op.alter_column("epochs", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("loss", existing_type=sa.VARCHAR(length=50), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # batch_alter_table: most SQLite versions have no ALTER COLUMN, so it rebuilds the table there;
    # PostgreSQL gets the same ALTER statements as before.
    with op.batch_alter_table("model_basic") as batch_op:
        batch_op.alter_column("loss", existing_type=sa.VARCHAR(length=50), nullable=False)
        batch_op.alter_column("epochs", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("metric", existing_type=sa.VARCHAR(length=50), nullable=False)
        batch_op.alter_column("optimizer", existing_type=sa.VARCHAR(length=50), nullable=False)
        batch_op.alter_column("training_split", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False)
        batch_op.alter_column("model_type", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("file_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
